import React from "react";
import { Document, Page, View, Text, Image, Svg, Rect, Line, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { fetchAsDataUrl } from "@/lib/reports/pdf";
import type { EmployeeAttendanceScore } from "./query";

const BARS_PER_PAGE = 20;
const CHART_WIDTH = 760;
const CHART_HEIGHT = 260;
const BAR_GAP = 6;

const styles = StyleSheet.create({
  page: { padding: 32, fontFamily: "Helvetica", fontSize: 9 },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 16, gap: 12 },
  logo: { width: 40, height: 40, objectFit: "contain" },
  companyName: { fontSize: 14, fontWeight: 700 },
  reportTitle: { fontSize: 11, color: "#444444", marginTop: 2 },
  meta: { fontSize: 8, color: "#666666", marginTop: 2 },
  chartWrap: { marginTop: 12, borderWidth: 1, borderColor: "#dddddd", padding: 12 },
  pageNote: { marginTop: 8, fontSize: 8, color: "#888888" },
});

function scoreColor(percentage: number): string {
  if (percentage >= 80) return "#16a34a";
  if (percentage >= 50) return "#f59e0b";
  return "#dc2626";
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

function BarChartSvg({ scores }: { scores: EmployeeAttendanceScore[] }) {
  const plotHeight = CHART_HEIGHT - 40; // leaves room for the score label above and name below
  const barWidth = Math.min(48, CHART_WIDTH / Math.max(scores.length, 1) - BAR_GAP);
  const totalWidth = Math.max(CHART_WIDTH, scores.length * (barWidth + BAR_GAP));

  return (
    <Svg width={totalWidth} height={CHART_HEIGHT}>
      <Line x1={0} y1={plotHeight + 20} x2={totalWidth} y2={plotHeight + 20} stroke="#cbd5e1" strokeWidth={1} />
      {scores.map((s, i) => {
        const barHeight = Math.max(2, (Math.min(100, s.percentage) / 100) * plotHeight);
        const x = i * (barWidth + BAR_GAP);
        const y = plotHeight + 20 - barHeight;
        const name = s.employeeName.length > 12 ? `${s.employeeName.slice(0, 11)}…` : s.employeeName;
        return (
          <React.Fragment key={s.employeeId}>
            <Text x={x} y={y - 6} style={{ fontSize: 7 }}>
              {Math.round(s.percentage)}%
            </Text>
            <Rect x={x} y={y} width={barWidth} height={barHeight} fill={scoreColor(s.percentage)} rx={2} />
            <Text x={Math.max(0, x - 2)} y={plotHeight + 32} style={{ fontSize: 6 }}>
              {name}
            </Text>
          </React.Fragment>
        );
      })}
    </Svg>
  );
}

interface AnalyticsChartPdfProps {
  companyName: string;
  logoDataUrl?: string | null;
  subtitle: string;
  generatedBy: string;
  generatedAt: string;
  pages: EmployeeAttendanceScore[][];
}

function AnalyticsChartPdfDocument({ companyName, logoDataUrl, subtitle, generatedBy, generatedAt, pages }: AnalyticsChartPdfProps) {
  return (
    <Document>
      {pages.map((pageScores, pageIndex) => (
        <Page key={pageIndex} size="A4" orientation="landscape" style={styles.page}>
          <View style={styles.header}>
            {/* eslint-disable-next-line jsx-a11y/alt-text -- @react-pdf/renderer's Image is a PDF node, not an HTML <img> */}
            {logoDataUrl ? <Image src={logoDataUrl} style={styles.logo} /> : null}
            <View>
              <Text style={styles.companyName}>{companyName}</Text>
              <Text style={styles.reportTitle}>Analytics — Attendance Performance</Text>
              <Text style={styles.meta}>
                {subtitle} · Generated by {generatedBy} on {generatedAt}
              </Text>
            </View>
          </View>

          <View style={styles.chartWrap}>
            {pageScores.length > 0 ? (
              <BarChartSvg scores={pageScores} />
            ) : (
              <Text>No attendance records for this period.</Text>
            )}
          </View>
          {pages.length > 1 ? (
            <Text style={styles.pageNote}>
              Page {pageIndex + 1} of {pages.length} — {BARS_PER_PAGE} employees per page
            </Text>
          ) : null}
        </Page>
      ))}
    </Document>
  );
}

export interface GenerateAnalyticsChartPdfParams {
  companyName: string;
  logoUrl?: string | null;
  subtitle: string;
  generatedBy: string;
  scores: EmployeeAttendanceScore[];
}

/** Renders the Analytics dashboard's ranked bar chart as a PDF image — a visual
 * snapshot of the board, distinct from the tabular Performance report (Reports
 * section), which lists the same underlying scores as rows instead of bars. */
export async function generateAnalyticsChartPdf(params: GenerateAnalyticsChartPdfParams): Promise<Buffer> {
  const logoDataUrl = params.logoUrl ? await fetchAsDataUrl(params.logoUrl) : null;
  const pages = chunk(params.scores, BARS_PER_PAGE);
  const doc = (
    <AnalyticsChartPdfDocument
      companyName={params.companyName}
      logoDataUrl={logoDataUrl}
      subtitle={params.subtitle}
      generatedBy={params.generatedBy}
      generatedAt={new Date().toLocaleString()}
      pages={pages.length > 0 ? pages : [[]]}
    />
  );
  return renderToBuffer(doc);
}
