import { prisma } from "@/lib/db/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getAttendanceSettings } from "@/lib/attendance/settings";
import { formatInTimeZone } from "date-fns-tz";
import { PageHeader } from "@/components/admin/PageHeader";
import { GenerateQrForm, DeactivateQrButton } from "./QrActions";

export const dynamic = "force-dynamic";

const STATUS_STYLES: Record<string, string> = {
  ACTIVE: "bg-green-100 text-green-700",
  SCHEDULED: "bg-blue-100 text-blue-700",
  EXPIRED: "bg-gray-200 text-gray-700",
  DEACTIVATED: "bg-red-100 text-red-700",
};

function dateRangeLabel(qr: { attendanceDate: Date; validUntil: Date }): string {
  const start = qr.attendanceDate.toISOString().slice(0, 10);
  const end = qr.validUntil.toISOString().slice(0, 10);
  return start === end ? start : `${start} – ${end}`;
}

function missingArtifacts(qr: { pdfUrl: string | null; pngUrl: string | null }): boolean {
  return !qr.pdfUrl && !qr.pngUrl;
}

export default async function QrPage() {
  const [offices, qrCodes, settings] = await Promise.all([
    prisma.office.findMany({ orderBy: { name: "asc" } }),
    prisma.attendanceQrCode.findMany({
      include: { office: true, generatedBy: true },
      orderBy: { createdAt: "desc" },
      take: 30,
    }),
    getAttendanceSettings(),
  ]);

  const todayStr = formatInTimeZone(new Date(), settings.timezone, "yyyy-MM-dd");

  return (
    <>
      <PageHeader>
        <h1 className="text-2xl font-bold">QR Codes</h1>
        <p className="text-sm text-muted-foreground">
          Attendance mode is <strong>{settings.attendanceMode.replace(/_/g, " ")}</strong>.{" "}
          {settings.attendanceMode === "QR_ONLY" ? (
            <span className="text-amber-700">
              QR_ONLY provides weaker physical-presence verification than QR_AND_NETWORK.
            </span>
          ) : null}
        </p>
      </PageHeader>
      <div className="space-y-6 px-4 py-6 sm:px-6 md:px-8">
      <Card>
        <CardHeader>
          <CardTitle>Generate QR</CardTitle>
        </CardHeader>
        <CardContent>
          <GenerateQrForm offices={offices} todayStr={todayStr} />
          {offices.length === 0 ? (
            <p className="mt-2 text-sm text-amber-700">Create an office first.</p>
          ) : null}
        </CardContent>
      </Card>

      {/* Mobile: card list */}
      <div className="space-y-2 md:hidden">
        {qrCodes.map((qr) => (
          <div key={qr.id} className="rounded-lg border bg-card p-4">
            <div className="flex items-start justify-between gap-2">
              <div className="min-w-0">
                <p className="font-medium">{qr.office.name}</p>
                <p className="text-xs text-muted-foreground">{dateRangeLabel(qr)}</p>
              </div>
              <span className={`shrink-0 rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_STYLES[qr.status]}`}>
                {qr.status}
              </span>
            </div>
            <p className="mt-2 text-xs text-muted-foreground">Generated by {qr.generatedBy.fullName}</p>
            <div className="mt-3 flex flex-wrap gap-4">
              {qr.pngUrl ? (
                <a href={qr.pngUrl} target="_blank" rel="noreferrer" className="text-sm text-primary hover:underline">
                  PNG
                </a>
              ) : null}
              {qr.pdfUrl ? (
                <a href={qr.pdfUrl} target="_blank" rel="noreferrer" className="text-sm text-primary hover:underline">
                  PDF
                </a>
              ) : null}
              {missingArtifacts(qr) ? (
                <span
                  className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800"
                  title="PDF/PNG generation failed for this QR code. It's still valid for clock-in — check the server's storage configuration to enable downloads."
                >
                  No files
                </span>
              ) : null}
              {qr.status === "ACTIVE" || qr.status === "SCHEDULED" ? (
                <DeactivateQrButton qrId={qr.id} className="text-sm text-red-600 hover:underline" />
              ) : null}
            </div>
          </div>
        ))}
        {qrCodes.length === 0 ? (
          <p className="rounded-lg border bg-card px-4 py-8 text-center text-sm text-muted-foreground">
            No QR codes generated yet.
          </p>
        ) : null}
      </div>

      {/* Desktop: table */}
      <div className="hidden overflow-x-auto rounded-lg border bg-card md:block">
        <table className="w-full text-sm">
          <thead className="border-b bg-muted/50 text-left text-xs uppercase text-muted-foreground">
            <tr>
              <th className="px-4 py-2">Office</th>
              <th className="px-4 py-2">Date</th>
              <th className="px-4 py-2">Status</th>
              <th className="px-4 py-2">Generated By</th>
              <th className="px-4 py-2" />
            </tr>
          </thead>
          <tbody>
            {qrCodes.map((qr) => (
              <tr key={qr.id} className="border-b last:border-0">
                <td className="px-4 py-2">{qr.office.name}</td>
                <td className="px-4 py-2">{dateRangeLabel(qr)}</td>
                <td className="px-4 py-2">
                  <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_STYLES[qr.status]}`}>
                    {qr.status}
                  </span>
                </td>
                <td className="px-4 py-2">{qr.generatedBy.fullName}</td>
                <td className="px-4 py-2">
                  <div className="flex justify-end gap-3">
                    {qr.pngUrl ? (
                      <a href={qr.pngUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline">
                        PNG
                      </a>
                    ) : null}
                    {qr.pdfUrl ? (
                      <a href={qr.pdfUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline">
                        PDF
                      </a>
                    ) : null}
                    {missingArtifacts(qr) ? (
                      <span
                        className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800"
                        title="PDF/PNG generation failed for this QR code. It's still valid for clock-in — check the server's storage configuration to enable downloads."
                      >
                        No files
                      </span>
                    ) : null}
                    {qr.status === "ACTIVE" || qr.status === "SCHEDULED" ? <DeactivateQrButton qrId={qr.id} /> : null}
                  </div>
                </td>
              </tr>
            ))}
            {qrCodes.length === 0 ? (
              <tr>
                <td colSpan={5} className="px-4 py-8 text-center text-muted-foreground">
                  No QR codes generated yet.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
      </div>
    </>
  );
}
