import React from "react";
import { Document, Page, View, Text, Image, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 32, fontFamily: "Helvetica", fontSize: 9 },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 16, gap: 12 },
  logo: { width: 40, height: 40, objectFit: "contain" },
  companyName: { fontSize: 14, fontWeight: 700 },
  reportTitle: { fontSize: 11, color: "#444444", marginTop: 2 },
  meta: { fontSize: 8, color: "#666666", marginTop: 2 },
  summary: { marginTop: 14, padding: 8, backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 3 },
  summaryTitle: { fontSize: 9, fontWeight: 700, marginBottom: 4 },
  summaryLine: { fontSize: 8, color: "#333333", marginTop: 2 },
  table: { display: "flex", flexDirection: "column", marginTop: 12, borderWidth: 1, borderColor: "#dddddd" },
  row: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#eeeeee" },
  headerRow: { flexDirection: "row", backgroundColor: "#f1f5f9", fontWeight: 700 },
  cell: { padding: 5, flex: 1, borderRightWidth: 1, borderColor: "#eeeeee" },
});

interface ReportPdfProps {
  companyName: string;
  logoDataUrl?: string | null;
  title: string;
  subtitle: string;
  generatedBy: string;
  generatedAt: string;
  summaryLines?: string[];
  headers: string[];
  rows: string[][];
}

function ReportPdfDocument({
  companyName,
  logoDataUrl,
  title,
  subtitle,
  generatedBy,
  generatedAt,
  summaryLines,
  headers,
  rows,
}: ReportPdfProps) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          {/* eslint-disable-next-line jsx-a11y/alt-text -- @react-pdf/renderer's Image is a PDF node, not an HTML <img> */}
          {logoDataUrl ? <Image src={logoDataUrl} style={styles.logo} /> : null}
          <View>
            <Text style={styles.companyName}>{companyName}</Text>
            <Text style={styles.reportTitle}>{title}</Text>
            <Text style={styles.meta}>
              {subtitle} · Generated by {generatedBy} on {generatedAt}
            </Text>
          </View>
        </View>

        {summaryLines?.length ? (
          <View style={styles.summary}>
            <Text style={styles.summaryTitle}>Summary</Text>
            {summaryLines.map((line, i) => (
              <Text key={i} style={styles.summaryLine}>
                {line}
              </Text>
            ))}
          </View>
        ) : null}

        <View style={styles.table}>
          <View style={styles.headerRow}>
            {headers.map((h) => (
              <Text key={h} style={styles.cell}>
                {h}
              </Text>
            ))}
          </View>
          {rows.map((row, i) => (
            <View key={i} style={styles.row}>
              {row.map((cell, j) => (
                <Text key={j} style={styles.cell}>
                  {cell}
                </Text>
              ))}
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );
}

export async function fetchAsDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const contentType = res.headers.get("content-type") ?? "image/png";
    const buffer = Buffer.from(await res.arrayBuffer());
    return `data:${contentType};base64,${buffer.toString("base64")}`;
  } catch {
    return null;
  }
}

export interface GenerateReportPdfParams {
  companyName: string;
  logoUrl?: string | null;
  title: string;
  subtitle: string;
  generatedBy: string;
  summaryLines?: string[];
  headers: string[];
  rows: string[][];
}

export async function generateReportPdf(params: GenerateReportPdfParams): Promise<Buffer> {
  const logoDataUrl = params.logoUrl ? await fetchAsDataUrl(params.logoUrl) : null;
  const doc = (
    <ReportPdfDocument
      companyName={params.companyName}
      logoDataUrl={logoDataUrl}
      title={params.title}
      subtitle={params.subtitle}
      summaryLines={params.summaryLines}
      generatedBy={params.generatedBy}
      generatedAt={new Date().toLocaleString()}
      headers={params.headers}
      rows={params.rows}
    />
  );
  return renderToBuffer(doc);
}
